### ISSUE TITLE
.kubeconfig file is not created during make install

### ISSUE THREAD

**Issue by plank-tools** [gitpod-io/gitpod-eks-guide#13]
I used my `root` aws credentials to deploy a gitpod cluster to us-east-2. It failed in the middle, complaining that the `.kubeconfig` file is a directory. I verified that an empty directory `.kubeconfig` was created in my current directory. 

```
unable to write kubeconfig , please retry with 'eksctl utils write-kubeconfig -n gitpod': unable to read existing kubeconfig file ".kubeconfig": error loading config file ".kubeconfig": read .kubeconfig: is a directory
```

When I created the `.kubeconfig` file in the current directory manually using `eksctl` and ran `make install` again, it ran successfully.

**Comment by aledbf** [comment]
Closing. Fixed in main
