### ISSUE TITLE
DNS Instructions

### ISSUE THREAD

**Issue by plank-tools** [gitpod-io/gitpod-eks-guide#14]
Please add dns configuration instructions. I'm struggling with accessing workspaces after I installed gitpod. Would be greate if you can include dns configuration instructions for those of us who're hosting gitpod in the cloud for our developers. 

Here's what I've tried so far. 

I've setup the CNAMES for `gitpod.my-domain`, `*.gitpod.my-domain`, `ws.gitpod.my-domain`, `*.ws.gitpod.mydomain`. None of them work.

**Comment by aledbf** [comment]
> Please add dns configuration instructions

Can you provide more detail about what are you doing? Did you enable [Route53](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/.env.example#L16)?

> None of them work.

Please provide more details about what are you doing, please.

**Comment by plank-tools** [comment]
> > Please add dns configuration instructions
> 
> Can you provide more detail about what are you doing? Did you enable [Route53](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/.env.example#L16)?
> If not, is the output of `dig -t cname gitpod.my-domain` returning the CNAME of the ALB?
> 
> > None of them work.
> 
> Please provide more details about what are you doing.

Finally got one configuration to work. Added CNAMEs for "*.gitpod.my-domain", *.ws.gitpod.my-domain, ws.gitpod.my-domain". I'm sure some of them are redundant, but it took a while for these CNAMEs to propagate.

**Comment by aningako** [comment]
> > > Please add dns configuration instructions
> > 
> > 
> > Can you provide more detail about what are you doing? Did you enable [Route53](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/.env.example#L16)?
> > If not, is the output of `dig -t cname gitpod.my-domain` returning the CNAME of the ALB?
> > > None of them work.
> > 
> > 
> > Please provide more details about what are you doing.
> 
> Finally got one configuration to work. Added CNAMEs for "*.gitpod.my-domain", *.ws.gitpod.my-domain, ws.gitpod.my-domain". I'm sure some of them are redundant, but it took a while for these CNAMEs to propagate. It looks like it was entirely a service provider issue. Closing.

you added these cnames and point it to your gitpod.my-domain?
