### ISSUE TITLE
Add a note about why not Terraform

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod-eks-guide#17]

**Comment by dmattia** [comment]
+1, I thought this was a bit odd to not include

**Comment by aledbf** [comment]
Closing. The official CLI for Amazon EKS is eksctl, and CDK is more flexible than Terraform.

The guide's goal is to install Gitpod in EKS, not to prescribe how to provision the cluster. Now that we are switching to a [go installer](https://github.com/gitpod-io/gitpod/tree/main/installer), after rendering the manifests feel free to use the tool of choice.
