### ISSUE TITLE
What is the need of custom AMI?

### ISSUE THREAD

**Issue by vavdoshka** [gitpod-io/gitpod-eks-guide#27]
I'm trying to integrate this solution into existing infra, I'm only allowed to use AWS managed AMIs in that EKS cluster.
I was trying to understand what limitations of standard managed AMI are triggered the creation of the custom AMI.
Based on my experiments I understood that at least version of Containerd should be > 1.5 due to the [registry host configs feature](https://github.com/containerd/containerd/blob/main/docs/hosts.md) which is being used to setup registy-facade.
I did not get any further, is there any other limitations?

**Comment by aledbf** [comment]
@vavdoshka the custom AMIs predate the containerd support from AWS managed AMIs. 

You should try to use the ones provided by AWS, creating the required `/etc/containerd/certs.d` directory

**Comment by vavdoshka** [comment]
@aledbf 
yes I did try and found that I got the certificate trust error, 
turned out the version of Containerd being [used](https://github.com/awslabs/amazon-eks-ami/blob/master/eks-worker-al2.json#L17) in the latest Amazon EKS AMI is **1.4.6** and as I understood the `/etc/containerd/certs.d` support was [implemented in 1.5](https://github.com/containerd/containerd/blob/main/docs/hosts.md?plain=1#L4).
If this is the only constraint I will wait for Containerd update to >1.5 in Amazon AMI and test it once again.

**Comment by szab100** [comment]
@aledbf is the `/etc/containerd/certs.d` needed because of the default internal registry using self-signed cert? If so, when configuring Gitpod to use an existing registry (such as Artifactory) that containerd is already configured to pull from without needing custom root certs, am I correct that this is not required?

**Comment by vavdoshka** [comment]
Hello @aledbf,

Any chance the Installer MVP can be tested to provide your with a feedback?
 https://github.com/gitpod-io/gitpod/milestone/16 (seems like 2 issues are still opened at this point of time, but these are non-blocking to get MVP run at least)

At the same time I don't see any references of it in the docs, and according to this ticket it seems the installer MVP is targeting GKE/AKS only https://github.com/gitpod-io/gitpod/issues/6422

Still, if possible to test on EKS what could be the pointers to start with?
