### ISSUE TITLE
Update AWS guide for the installer

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/gitpod-eks-guide#28]
- [x] Update setup for installer vs helm
- [x] CDK Library for the installer
- [ ] Update README

**Comment by aledbf** [comment]
> CDK Library for the installer

I am not sure about this point. I found the lambda function approach too complex for what it does. Similar to what we have in the other guides, [this way](https://github.com/gitpod-io/gitpod-eks-guide/pull/29/files#diff-4209d788ad32c40cbda3c66b3de47eefb929308ca703bb77a6382625986add17R184-R196) is simple enough to run after the CDK scripts are done. WDYT?

**Comment by metcalfc** [comment]
I’m not familiar enough with the ups and downs of cdk development. Looking forward so long as we have a good path for long term maintaining our own method vs using a the ease of a community developed library.
