### ISSUE TITLE
CREATE_FAILED   Custom::AWSCDK-EKS-HelmChart    jaegerBaseClusterc

### ISSUE THREAD

**Issue by Hosh20** [gitpod-io/gitpod-eks-guide#34]
### Bug description

while i install gitpod from latest Repo i got this error

9:07:41 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | jaegerBaseClusterc...ratorchart65DD0125
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "jaeger-operator" does not exist. Installing
it now.\nmanifest_sorter.go:192: info: skipping unknown hook: "crd-install"\nError: timed out waiting for the condition\n'

Logs: /aws/lambda/Addons-AddonsjaegerBaseClusterEED1-Handler886CB40B-fBTaGMxfVlZI

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 4a0a8ff0-4d75-440a-942c-cd400ced58cc)

        new CustomResource (/gitpod/node_modules/@aws-cdk/core/lib/custom-resource.ts:36:21)
        \_ new HelmChart (/gitpod/node_modules/@aws-cdk/aws-eks/lib/helm-chart.ts:69:5)
        \_ ImportedCluster.addHelmChart (/gitpod/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:347:12)
        \_ new Jaeger (/gitpod/lib/charts/jaeger.ts:12:35)
        \_ new AddonsStack (/gitpod/lib/addons.ts:23:9)
        \_ Object.<anonymous> (/gitpod/bin/provision.ts:35:16)
        \_ Module._compile (internal/modules/cjs/loader.js:1072:14)
        \_ Module.m._compile (/gitpod/node_modules/ts-node/src/index.ts:1310:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
        \_ Object.require.extensions.<computed> [as .ts] (/gitpod/node_modules/ts-node/src/index.ts:1313:12)
        \_ Module.load (internal/modules/cjs/loader.js:937:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:778:12)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
        \_ main (/gitpod/node_modules/ts-node/src/bin.ts:331:12)
        \_ Object.<anonymous> (/gitpod/node_modules/ts-node/src/bin.ts:482:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1072:14)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
        \_ Module.load (internal/modules/cjs/loader.js:937:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:778:12)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
        \_ /usr/local/share/.config/yarn/global/node_modules/npx/node_modules/libnpx/index.js:268:14

 ❌  Addons failed: Error: The stack named Addons failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMP                                                                     LETE
    at Object.waitForStackDeploy (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.deployStack (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/api/deploy-stack.ts:306:26)
    at CdkToolkit.deploy (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:184:24)
    at initCommandLine (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:218:9)
The stack named Addons failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE

![image](https://user-images.githubusercontent.com/5073211/144764283-b8ee5163-729f-44f8-8290-712762e40c58.png)

### Steps to reproduce

make install

### Expected behavior

created successfully

**Comment by linuxpoor3** [comment]
getting the same issue using `make install`

![image](https://user-images.githubusercontent.com/95272549/144805142-7b4a94a9-cbaf-43d2-959a-885ff3473af6.png)


```
us-west-2    ami-04a6d2a3b0d131841
us-west-1    ami-0f3e6671ef1ede777
```

**Comment by aledbf** [comment]
Closing. Please pull the latest changes from the repository and run `make install`.
